mail_login_enabled: 1
mail_login_override_login_labels: 1
mail_login_username_title: 'Login por tu email'
mail_login_username_description: 'Por for usar tu correo electrónic para login.'
_core:
  default_config_hash: SMMHLGfy4YoZHXabFVqh8vjsvM_MzWgohArG_gXaIXQ
langcode: es
